# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://10.201.35.4:8080/api/v1/packageValidation/reqAndFunctionPointInfo?OANumber=NBXQX-2021-40
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVHSGxLOFJuaUFFcldrN0VVYjRaaHciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MzY2MDU1OTYsImV4cCI6MTYzNjYxMjc5NiwiaXNzIjoiaHR0cDovLzE3Mi4yMS43Mi4xNzo4MDg4IiwiYXVkIjpbImh0dHA6Ly8xNzIuMjEuNzIuMTc6ODA4OC9yZXNvdXJjZXMiLCJkZXZfY2VudGVyX2FwaSJdLCJjbGllbnRfaWQiOiJiZGRfZCIsInNjb3BlIjpbImRldl9jZW50ZXJfYXBpIl19.gUahjngG35obAJ0eApth2-H03YjnYCSD8o37pgpeB_sSB3bXB56YoL4kB1qdCFgjTQi5piFa-qrVNoMLiJwYzXqwrTOm9FSiYK3kzR1b6q2HNvKbiFchOvt9-PVnj1OWj9WII0nZIlkJ17dkdJ7Wu0pUKcTivAma4dw5ZQgoLRcSsb1laiGUu2o9RzN2BjRp5fow7gIyCPt5xIM5ziU4mC6LQMNFZgANnFeq2xiLXwZERdFYu3p5fN5VupxjxvdKburU0IxzXC23EHNgvcHkOZCSPwKRkmVVAaWedCBiQ5PyfNBNcq2IELCJhBqCUJRI1w9IudlvyRmN0xmEmt3l2Q
###

POST http://10.201.35.4:8080/api/v1/packageValidation/packageInfo
Content-Type: application/json;charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVHSGxLOFJuaUFFcldrN0VVYjRaaHciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MzQxNzY0MjYsImV4cCI6MTYzNDE4MzYyNiwiaXNzIjoiaHR0cDovLzE3Mi4yMS43Mi4xNzo4MDg4IiwiYXVkIjpbImh0dHA6Ly8xNzIuMjEuNzIuMTc6ODA4OC9yZXNvdXJjZXMiLCJkZXZfY2VudGVyX2FwaSJdLCJjbGllbnRfaWQiOiJiZGRfZCIsInNjb3BlIjpbImRldl9jZW50ZXJfYXBpIl19.fY4vUiLOIOR9Uy8BoeyWKXzb4bno1I-_OZQuLk8oEMPWxR93wN1JQX5tDRcZ5VqTYq_2RHV8y4t2t_r7q3oGE_kQheZvWHztyv7k5HXXQs3lID1G22oq1FCgpD3nZYsdbNbKwObKDeegIgABsHJoi8mVOIHSR3yiFxtClr_2jDBfqk4ZwGSQQwwTzeZCsmILlSDn-zLFcOryz3SWmvVImwrsYrKROsdHNDl2k4CtoHJ_iLAnsWqRs6KUaQwxUB5Oz9QfgtmbNrM9Ilu_kiLHcIB3PkSWttxZkBe82kmlrbF_gH75phkmR8PP3TYwNxBC59LnC4-hTpfVGUCrPV_96A

{
  "packageName": "XXXXXXXX.zip",
  "packagePath": "/UPSCM/sjfwtd/XXXXXXXX.zip",
  "packageSize": 21321321,
  "functionPointIdList": [9530,9531,6698]
}

###

POST http://10.201.35.4:8080/api/v1/packageValidation/ValidateResult
Content-Type: application/json;charset=utf-8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InRSVHQtWk5DaHlSTmJfczdIYng2bVEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MzI3NDUzODMsImV4cCI6MTYzMjc1MjU4MywiaXNzIjoiaHR0cDovLzE3Mi4yMS43Mi4xNzo4MDg4IiwiYXVkIjpbImh0dHA6Ly8xNzIuMjEuNzIuMTc6ODA4OC9yZXNvdXJjZXMiLCJkZXZfY2VudGVyX2FwaSJdLCJjbGllbnRfaWQiOiJiZGRfZCIsInNjb3BlIjpbImRldl9jZW50ZXJfYXBpIl19.SFmF2Xe9vq7aFGLG84EU1-rO4gEM_52L1mW4shLFso61xOsSebHolmqVjx-E_vYm95qrgbSCvsC1Zh9UlTG5T3K9mMIAeMltrgrqyRI2UjS8v4V7rGn7CB_zVVIZEdT27nRKNNzzViOnG6pM3njrcMnf3n5bHJrtyUnkMBB22T4Ylha67q9nlL0C6mxK5mtzoPcbzKWG0mdcpqD1lKUD8ktJJNIkbP5cwt7yIaM-qPQoc-v6wanxCzdbVQ5IXhbJDeeZLcxgTmGCr9qC-Efr8VFBzZhpKPzR-J6bNcsYoKuSUw9nq8CpEV7WoLB95sRWKfBZuytUZMb6f5aRmD39GA

{
  "functionPointId": 9531,
  "packageName": "1243.zip",
  "result": false
}

###

GET http://172.21.224.43:80/api/v1/packageValidation/reqAndFunctionPointInfo?OANumber=NBXQX-2021-40
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNGOTg4Q0UwNUUzNTI1ODUxODYwNTZDNzZCMDk5ODNFQkY5NjNEOTMiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJQNWlNNEY0MUpZVVlZRmJIYXdtWVByLVdQWk0ifQ.eyJuYmYiOjE2MzQxNzcyNzAsImV4cCI6MTYzNDE4NDQ3MCwiaXNzIjoiaHR0cHM6Ly90ZWNocG9ydGFsLm9hLnVuaW9ucGF5LmNvbSIsImF1ZCI6WyJodHRwczovL3RlY2hwb3J0YWwub2EudW5pb25wYXkuY29tL3Jlc291cmNlcyIsImRldl9jZW50ZXJfYXBpIl0sImNsaWVudF9pZCI6ImJkZF9kIiwic2NvcGUiOlsiZGV2X2NlbnRlcl9hcGkiXX0.Id9oEd11OiLWl80h59lWqiQhp59Jg3lSo-4PhlpZmLwRpiXDBPdsQa9ogQRpsEQbg6el-XPkLjEToFDH7vJQRkvEXC0Nj1FR5bov1frT8N14xfI4I-IhchSAxX8iLHJ5BcjvSZf0ko0oGLnQ3Xv88_sT8g1wDycRqEI7SFCUjrwmfr3yAjNNV-Pn1D3so2OIwbcU45X6s1ajKvKHbKfTVa2Q8k33CXohHNEocHTOJbtjqju3Xqv4BFtjNNVuHy6vEVAA0U-8lfFMvD9xCT8brjMmezgvdzFoXy08JlTgp4yNF50aCO4plNbds2Sj9Cpj7ZYVfbKwHnS8O0C-0PKx5w
###